001 add books
DmytroStoliaruk/BookHub pull request #1
Opened 2023-10-13 05:58 UTC by DmytroStoliaruk

2023-10-13 12:25 UTC, DmytroStoliaruk commented
Hi! After init commit I ran 'rubocop' and in most files \" was replaced with \'. This is the reason for a big list of changes. Probably I shouldn't do it but I did. Pleace just skip this code.

2023-10-14 08:20 UTC, DmytroStoliaruk commented
I added a new commit to this pull request where add .rubocop.yml and set a new rule for single_quotes. As you recommended at your first meeting use double_quotes I replaced all single_quotes with double_quotes. As a result code for review became shorter... :)

2023-10-17 19:20 UTC, DmytroStoliaruk commented
17.10.23 update before review, after the expert's recommendation for other teammates

2023-10-25 16:16 UTC, DmytroStoliaruk commented
Update after comments and delete gitignore file

2023-10-29 14:33 UTC, loqimean commented on app/assets/stylesheets/application.tailwind.css
> +  display: -webkit-box;
половина всіх цих стилів може бути написана в стилі теілвінда, а якщо вже і треба саме такий стиль, бо чогось нема, то на то є окремий файл + я вам казав розділяти все, тайпографі окремо, кнопки окремо і тд

2023-10-29 14:33 UTC, loqimean commented on app/helpers/application_helper.rb
повертай

2023-10-29 14:33 UTC, loqimean commented on app/views/books/_cover.html.erb
> +<% end %>
нема нової строки

2023-10-29 14:33 UTC, loqimean commented on app/views/books/_form.html.erb
> +  <%= simple_form_for @book, defaults: { input_html: { class: "w-full" } } do |f| %>
де шлях, куди ти посилаєш цю форму?))

2023-10-29 14:33 UTC, loqimean commented on app/views/books/new.html.erb
> +
не треба цієї нової строки

2023-10-29 14:33 UTC, loqimean commented on app/views/layouts/application.html.erb
> +
видаляй пусту строку цю

2023-10-29 14:33 UTC, loqimean commented on bin/dev
це ще чому видалено?

2023-10-29 14:33 UTC, loqimean commented on bin/importmap
а це чому???

2023-10-29 14:33 UTC, loqimean commented on bin/bundle
аналогічно

2023-10-29 14:33 UTC, loqimean commented on bin/rails
і тут

2023-10-29 14:33 UTC, loqimean commented on bin/rake
і тут

2023-10-29 14:33 UTC, loqimean commented on bin/setup
і тут

2023-10-29 14:33 UTC, loqimean commented on config/initializers/filter_parameter_logging.rb
> +Rails.application.config.filter_parameters += %i[
видаляй ці приколи з відсотком

2023-10-29 14:33 UTC, loqimean commented on config/initializers/inflections.rb
а це чому видалив???

2023-10-29 14:33 UTC, loqimean commented on config/routes.rb
> +  root "books#index"
це зазвичай зверху знаходиться

2023-10-29 14:33 UTC, loqimean commented on db/seeds.rb
а це чому видалено? і чому у тебе не сідається база?

2023-10-29 14:33 UTC, loqimean commented on spec/models/book_spec.rb
> +  it { should validate_presence_of(:isbn) }
https://www.betterspecs.org/

`should` давно устарів і його не юзають

2023-10-29 14:33 UTC, loqimean commented on spec/models/book_spec.rb
> +    expect(valid_book).to be_valid
а на кріейт взагалі нема сенсу тестувати валідність, якщо у тебе при не валдіному рекорді буде ерора і він не створиться

2023-10-29 14:33 UTC, loqimean commented on spec/requests/books_spec.rb
> +      get books_url
use `_path`

2023-10-29 14:33 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response).to be_successful
перевіряй, що у тебе хоть щось на тій сторінці індекса є

2023-10-29 14:33 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response).to be_successful
і так на всіх сторінках, де є рекорд

2023-10-29 14:33 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect do
а де тестування флеша?)

2023-10-29 14:33 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response).to be_unprocessable
де тестування флеша?

2023-10-29 14:33 UTC, loqimean commented on tmp/.keep
чому це видалено?

2023-10-29 14:33 UTC, loqimean commented on tmp/pids/.keep
чому видалено?

2023-10-29 14:33 UTC, loqimean commented on tmp/storage/.keep
чому видалено??

2023-10-29 17:27 UTC, DmytroStoliaruk commented on app/assets/stylesheets/application.tailwind.css
> +  display: -webkit-box;
fixed

2023-10-29 17:32 UTC, DmytroStoliaruk commented on app/helpers/application_helper.rb
fixed

2023-10-29 17:33 UTC, DmytroStoliaruk commented on app/views/books/_cover.html.erb
> +<% end %>
fixed

2023-10-29 17:41 UTC, DmytroStoliaruk commented on app/views/books/_form.html.erb
> +  <%= simple_form_for @book, defaults: { input_html: { class: "w-full" } } do |f| %>
fixed

2023-10-29 17:42 UTC, DmytroStoliaruk commented on app/views/books/new.html.erb
> +
fixed

2023-10-29 17:43 UTC, DmytroStoliaruk commented on app/views/layouts/application.html.erb
> +
fixed

2023-10-29 17:45 UTC, DmytroStoliaruk commented on bin/dev
corrected gitignore

2023-10-29 17:45 UTC, DmytroStoliaruk commented on bin/importmap
corrected gitignore

2023-10-29 17:46 UTC, DmytroStoliaruk commented on bin/bundle
corrected gitignore

2023-10-29 17:46 UTC, DmytroStoliaruk commented on bin/rails
corrected gitignore

2023-10-29 17:46 UTC, DmytroStoliaruk commented on bin/rake
corrected gitignore

2023-10-29 17:46 UTC, DmytroStoliaruk commented on bin/setup
corrected gitignore

2023-10-29 17:49 UTC, DmytroStoliaruk commented on config/initializers/filter_parameter_logging.rb
> +Rails.application.config.filter_parameters += %i[
fixed

2023-10-29 17:51 UTC, DmytroStoliaruk commented on config/initializers/inflections.rb
він був пустим. повернув

2023-10-29 17:54 UTC, DmytroStoliaruk commented on config/routes.rb
> +  root "books#index"
fixed

2023-10-29 18:01 UTC, DmytroStoliaruk commented on db/seeds.rb
fixed

2023-10-29 18:03 UTC, DmytroStoliaruk commented on tmp/.keep
вилучив з gitignire каталог tmp

2023-10-29 18:04 UTC, DmytroStoliaruk commented on tmp/pids/.keep
вилучив з gitignire каталог tmp

2023-10-29 18:04 UTC, DmytroStoliaruk commented on tmp/pids/.keep
вилучив з gitignire каталог tmp

2023-10-29 18:04 UTC, DmytroStoliaruk commented on tmp/storage/.keep
вилучив з gitignire каталог tmp

2023-10-29 18:43 UTC, DmytroStoliaruk commented on spec/models/book_spec.rb
> +  it { should validate_presence_of(:isbn) }
fixed

2023-10-29 18:44 UTC, DmytroStoliaruk commented on spec/models/book_spec.rb
> +    expect(valid_book).to be_valid
прибрав

2023-10-29 18:46 UTC, DmytroStoliaruk commented on spec/requests/books_spec.rb
> +      get books_url
fixed

2023-10-29 19:20 UTC, DmytroStoliaruk commented on spec/requests/books_spec.rb
> +      expect do
fixed

2023-10-29 20:10 UTC, DmytroStoliaruk commented on spec/requests/books_spec.rb
> +      expect(response).to be_unprocessable
fixed

2023-11-01 08:00 UTC, loqimean requested changes

2023-11-01 08:00 UTC, loqimean commented on .vscode/settings.json
> +}
де нова строка?)

2023-11-01 08:00 UTC, loqimean commented on app/assets/stylesheets/tags.tailwind.css
> +  main{
```suggestion
  main {
```

2023-11-01 08:00 UTC, loqimean commented on app/assets/stylesheets/tags.tailwind.css
> +  main{
і так скрізь

2023-11-01 08:00 UTC, loqimean commented on config/routes.rb
> +  root "books#index"
не фіксед)

2023-11-01 08:00 UTC, loqimean commented on spec/models/book_spec.rb
> +
```suggestion
```

2023-11-01 08:00 UTC, loqimean commented on tmp/pids/server.pid
чому цей файл тут? він не мав би бути тут

2023-11-01 08:00 UTC, loqimean commented on tmp/development_secret.txt
теж

2023-11-01 08:42 UTC, DmytroStoliaruk commented on .vscode/settings.json
> +}
fixed

2023-11-01 08:49 UTC, DmytroStoliaruk commented on spec/models/book_spec.rb
> +
прибрав

2023-11-01 11:17 UTC, DmytroStoliaruk commented on config/routes.rb
> +  root "books#index"
сорі, піднів догори

2023-11-01 11:21 UTC, DmytroStoliaruk commented on app/assets/stylesheets/tags.tailwind.css
> +  main{
поправив

2023-11-01 11:22 UTC, DmytroStoliaruk commented on tmp/pids/server.pid
прибрав

2023-11-01 11:22 UTC, DmytroStoliaruk commented on tmp/development_secret.txt
прибрав

2023-11-02 08:21 UTC, loqimean requested changes

2023-11-02 08:21 UTC, loqimean commented on app/assets/stylesheets/application.tailwind.css
> +
вниз перемісти)

2023-11-02 08:21 UTC, loqimean commented on app/assets/stylesheets/base.tailwind.css
що це ща назва така?) давай так: `app/assets/stylesheets/layers/base.css`

2023-11-02 08:21 UTC, loqimean commented on spec/models/book_spec.rb
> +
```suggestion
```

2023-11-02 08:21 UTC, loqimean commented on spec/models/book_spec.rb
> +  end
```suggestion
  let(:invalid_book) { build(:book, :empty_title) }

  it "is not valid with an empty title" do
    expect(invalid_book).not_to be_valid
  end

```

2023-11-02 08:21 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response.body).to include(book.title)
а де перевірка статусу?)

2023-11-02 08:21 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response.body).to include(book.title)
і так скрізь

2023-11-02 08:21 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(flash[:notice]).to eq("Book was successfully created.")
а редірект?)

2023-11-02 08:21 UTC, loqimean commented on spec/requests/books_spec.rb
> +      }.to_not change(Book, :count)
мулті-лайн блок

2023-11-02 08:21 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response.body).to include("can&#39;t be blank")
не гуд), юзай escapeHTML

2023-11-02 08:28 UTC, DmytroStoliaruk commented on app/assets/stylesheets/application.tailwind.css
> +
перемістив

2023-11-02 08:30 UTC, DmytroStoliaruk commented on app/assets/stylesheets/base.tailwind.css
поміняв.

2023-11-02 08:31 UTC, DmytroStoliaruk commented on spec/models/book_spec.rb
> +
прибрав

2023-11-02 08:35 UTC, DmytroStoliaruk commented on spec/requests/books_spec.rb
> +      expect(response.body).to include("can&#39;t be blank")
поправив

2023-11-02 08:36 UTC, DmytroStoliaruk commented on spec/requests/books_spec.rb
> +      }.to_not change(Book, :count)
поправив

2023-11-02 08:38 UTC, DmytroStoliaruk commented on spec/requests/books_spec.rb
> +      expect(flash[:notice]).to eq("Book was successfully created.")
додав

2023-11-02 08:45 UTC, DmytroStoliaruk commented on spec/requests/books_spec.rb
> +      expect(response.body).to include(book.title)
поправив

2023-11-02 08:47 UTC, DmytroStoliaruk commented on spec/models/book_spec.rb
> +  end
додав строку

2023-11-05 10:05 UTC, loqimean requested changes
Пару коментів

2023-11-05 10:05 UTC, loqimean commented on Gemfile
> +  gem "rspec-rails", "~> 5.0"
Тобі точно потрібні цей гем в девелопменті?

2023-11-05 10:05 UTC, loqimean commented on Gemfile
> +  gem "shoulda-matchers", "~> 4.0"
Ці теж

2023-11-05 10:05 UTC, loqimean commented on app/assets/stylesheets/application.tailwind.css
> +@import "./flash.css";
Перемісти їх в якусь папку, щоб не мішати файли

2023-11-05 11:34 UTC, DmytroStoliaruk commented on app/assets/stylesheets/application.tailwind.css
> +@import "./flash.css";
fixed

2023-11-05 11:38 UTC, DmytroStoliaruk commented on Gemfile
> +  gem "rspec-rails", "~> 5.0"
fixed

2023-11-05 11:38 UTC, DmytroStoliaruk commented on Gemfile
> +  gem "shoulda-matchers", "~> 4.0"
fixed

2023-11-05 12:14 UTC, loqimean requested changes
Останній комент)

2023-11-05 12:14 UTC, loqimean commented on app/assets/stylesheets/application.tailwind.css
> +@import "./styles/flash.css";
Розмісти в якійсь папці, наприклад components, чи типу того, бо styles/styles таке собі)

2023-11-05 12:18 UTC, DmytroStoliaruk commented on app/assets/stylesheets/application.tailwind.css
> +@import "./styles/flash.css";
fixed

2023-11-05 12:20 UTC, loqimean approved these changes

2023-11-05 12:45 UTC, merged