003 active storage
DmytroStoliaruk/BookHub pull request #3
Opened 2023-11-07 15:13 UTC by DmytroStoliaruk

Add Active Storage.
Change views for using it.
Add tests.

2023-11-08 09:02 UTC, loqimean requested changes

2023-11-08 09:02 UTC, loqimean commented on app/controllers/books_controller.rb
> +
```suggestion
```

2023-11-08 09:02 UTC, loqimean commented on app/views/books/_cover.html.erb
> +      <% end %>
тобто якщо нема картинки, то ми показуємо контент, а якщо є, то достатньо і картинки?)

2023-11-08 12:15 UTC, DmytroStoliaruk commented on app/views/books/_cover.html.erb
> +      <% end %>
так, в індексі передбачається показ тільки обкладинок. якщо вона не завантажена, то показується шаблон на який виводиться назва автот та номер. Більше інформації в шоу... це виглядає тесь так...
<img width="1289" alt="Screenshot 2023-11-08 at 14 14 13" src="https://github.com/DmytroStoliaruk/BookHub/assets/35365419/2766a215-4554-4589-8684-c527f416c1f5">

2023-11-08 12:20 UTC, DmytroStoliaruk commented on app/controllers/books_controller.rb
> +
прибрав

2023-11-11 10:36 UTC, loqimean approved these changes

2023-11-11 10:36 UTC, loqimean commented on app/views/books/_cover.html.erb
> +      <% end %>
а, ну якщо так, то окей

2023-11-12 11:29 UTC, merged